#!/bin/sh

usage() {
    usage="Usage: $0 [date] general|steering"
    test $# -eq 1 && printf '%s\n' "$1" 1>&2
    printf "%s\n" "$usage" 1>&2
    exit 1
}

edit() {
    if [ -n "$EDITOR" ]; then
        "$EDITOR" "$source"
    elif [ -n "$VISUAL" ]; then
        "$VISUAL" "$source"
    elif type vim >/dev/null 2>&1; then
        vim "$source"
    elif type vi >/dev/null 2>&1; then
        vi "$source"
    elif type nano >/dev/null 2>&1; then
        nano "$source"
    else
        printf "Please edit %s, then hit ENTER\n" "$source"
        read DONE
    fi
}

if [ "$#" -eq 2 ]; then
    date="$1"
    general_or_steering="$2"
elif [ "$#" -eq 1 ]; then
    date="today"
    general_or_steering="$1"
else
    usage
fi

echo "$general_or_steering" |
    grep -e '^general$' -e '^steering$' >/dev/null ||
    usage "invalid meeting type $general_or_steering"

fmt_date="$(date -d "$date" +'%Y-%m-%d')"
test -n "$fmt_date" || usage

title="DNA-minutes-$fmt_date-$general_or_steering"
human_title="$fmt_date DNA $general_or_steering Meeting"
source="minutes/$title.rst"
build="minutes/build/$title"

test -e "$source" ||
    sed "s/__TITLE__/$human_title/" template.rst >"$source"

edit "$source"
pandoc -o "$build".docx "$source"
pandoc -o "$build".pdf "$source"

cat <<END
   Place
     $build.docx 
   and 
     $build.pdf
   in 
     https://drive.google.com/drive/folders/1JjvNrcLcTTte-pRLKc2ocCXk_tvgmMGu?usp=drive_link
END
